export function buildDefaultRules() {
  return [
    {
      rule_type: "count_rule",
      scope: "coronary",
      title: "冠状动脉支架置入费按血管计价",
      trigger_keywords: ["支架", "冠脉支架", "LAD", "RCA", "LCX", "LM"],
      target_item_name: "冠状动脉支架置入费",
      rule_text: "冠状动脉支架置入费按血管计价，不按支架枚数计价。",
      risk_level: "normal",
      active: 1,
    },
    {
      rule_type: "exclusion_rule",
      scope: "coronary",
      title: "同一冠脉血管支架和普通球囊不重复",
      trigger_keywords: ["支架", "球囊"],
      target_item_name: "冠状动脉支架置入费",
      rule_text: "同一冠脉血管已收支架置入费时，不与冠状动脉球囊扩张费同时收取。",
      risk_level: "warning",
      active: 1,
    },
    {
      rule_type: "count_rule",
      scope: "neuro",
      title: "脑血管造影 3 根及以下按 1 次",
      trigger_keywords: ["脑血管造影", "全脑造影", "造影根"],
      target_item_name: "脑血管造影费",
      rule_text: "脑血管造影费为3根及以下血管按1次，超过3根每增加1根按33%加收，一次收费不得超过7280元。",
      risk_level: "normal",
      active: 1,
    },
    {
      rule_type: "count_rule",
      scope: "neuro",
      title: "脊髓血管造影 4 根及以下按 1 次",
      trigger_keywords: ["脊髓血管造影", "脊髓造影"],
      target_item_name: "脊髓血管造影费",
      rule_text: "脊髓血管造影费为4根及以下血管按1次，超过4根每增加1根按25%加收，一次收费不得超过11970元。",
      risk_level: "normal",
      active: 1,
    },
    {
      rule_type: "addon_rule",
      scope: "neuro",
      title: "颅内血管加收提示",
      trigger_keywords: ["颅内", "脑静脉窦"],
      target_item_name: "颅内血管",
      rule_text: "脑静脉窦扩张或支架置入适用颅内血管加收，需在手术记录中写明部位。",
      risk_level: "warning",
      active: 1,
    },
    {
      rule_type: "extension_rule",
      scope: "all",
      title: "扩展项目不代表额外加价",
      trigger_keywords: ["扩展"],
      target_item_name: "",
      rule_text: "扩展项目只扩展适用范围，通常按主项目执行，不代表独立加价，需按院内医保收费口径确认。",
      risk_level: "warning",
      active: 1,
    },
    {
      rule_type: "mapping_rule",
      scope: "coronary",
      title: "冠脉 CTO 逆向再通挂靠",
      trigger_keywords: ["CTO", "慢性完全闭塞", "逆向开通", "逆向再通"],
      target_item_name: "冠状动脉慢性完全闭塞血管逆向再通治疗费",
      rule_text: "特殊术式没有完全同名项目时，按打通慢性闭塞血管的本质动作挂靠。",
      risk_level: "normal",
      active: 1,
    },
    {
      rule_type: "mapping_rule",
      scope: "neuro",
      title: "颅内动脉瘤弹簧圈或支架辅助挂靠",
      trigger_keywords: ["颅内动脉瘤", "弹簧圈", "支架辅助", "密网支架"],
      target_item_name: "颅内动脉瘤栓塞费",
      rule_text: "按堵住瘤腔或病变血管的本质动作挂靠颅内动脉瘤栓塞费。",
      risk_level: "warning",
      active: 1,
    },
    {
      rule_type: "mapping_rule",
      scope: "neuro",
      title: "脑静脉窦支架挂靠",
      trigger_keywords: ["脑静脉窦", "静脉窦支架"],
      target_item_name: "脑血管支架置入费",
      rule_text: "脑静脉窦支架置入按支架置入动作本质挂靠，并提示颅内血管加收。",
      risk_level: "warning",
      active: 1,
    },
    {
      rule_type: "manual_review_rule",
      scope: "all",
      title: "未导入收费标准组别",
      trigger_keywords: ["肿瘤", "下肢", "外周血管"],
      target_item_name: "",
      rule_text: "当前 Excel 未完整导入该组收费标准，不要乱匹配，请上传对应价格表后启用。",
      risk_level: "high",
      active: 1,
    },
  ];
}
